package main

import (
	"crypto/sha256"
	"encoding/hex"
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"sort"
	"strconv"
	"strings"
)

var (
	functionFuzzDictIntegerPattern    = regexp.MustCompile(`-?\b(0[xX][0-9A-Fa-f]+|\d+)\b`)
	functionFuzzDictStringLiteral     = regexp.MustCompile(`"((?:\\.|[^"\\])*)"`)
	functionFuzzDictIdentifierAllCaps = regexp.MustCompile(`\b[A-Z][A-Z0-9_]{2,}\b`)
)

type functionFuzzDictEntry struct {
	Token    string
	Origin   string
	Priority int
}

type functionFuzzCorpusSeed struct {
	Name        string `json:"name"`
	Scenario    string `json:"scenario,omitempty"`
	ParamClass  string `json:"param_class,omitempty"`
	ParamName   string `json:"param_name,omitempty"`
	Rule        string `json:"rule"`
	Size        int    `json:"size"`
	Sha256      string `json:"sha256"`
	Origin      string `json:"origin,omitempty"`
	SourceFile  string `json:"source_file,omitempty"`
	SourceLine  int    `json:"source_line,omitempty"`
	Description string `json:"description,omitempty"`
}

type functionFuzzCorpusManifest struct {
	GeneratedAt string                   `json:"generated_at,omitempty"`
	RunID       string                   `json:"run_id,omitempty"`
	Target      string                   `json:"target,omitempty"`
	Profile     string                   `json:"profile,omitempty"`
	Seeds       []functionFuzzCorpusSeed `json:"seeds"`
	Dictionary  []string                 `json:"dictionary,omitempty"`
}

func functionFuzzWriteDictionary(run FunctionFuzzRun, dictPath string) (int, error) {
	entries := functionFuzzCollectDictionaryEntries(run)
	if len(entries) == 0 {
		_ = os.Remove(dictPath)
		return 0, nil
	}
	if err := os.MkdirAll(filepath.Dir(dictPath), 0o755); err != nil {
		return 0, err
	}
	var b strings.Builder
	b.WriteString("# Auto-generated by Kernforge source-derived fuzz dictionary\n")
	b.WriteString("# Format: libFuzzer dictionary (quoted bytes with optional name= prefix)\n")
	b.WriteString("# Source: code_observations, branch_outcomes, sink_signals, parameter_strategies, virtual_scenarios\n\n")
	written := 0
	for _, entry := range entries {
		line := functionFuzzRenderDictionaryLine(entry)
		if line == "" {
			continue
		}
		b.WriteString(line)
		b.WriteByte('\n')
		written++
	}
	if written == 0 {
		_ = os.Remove(dictPath)
		return 0, nil
	}
	if err := os.WriteFile(dictPath, []byte(b.String()), 0o644); err != nil {
		return 0, err
	}
	return written, nil
}

func functionFuzzCollectDictionaryEntries(run FunctionFuzzRun) []functionFuzzDictEntry {
	seen := map[string]int{}
	out := []functionFuzzDictEntry{}
	add := func(entry functionFuzzDictEntry) {
		entry.Token = strings.TrimSpace(entry.Token)
		if entry.Token == "" {
			return
		}
		key := strings.ToLower(entry.Token) + "|" + entry.Origin
		if prior, ok := seen[key]; ok {
			if entry.Priority > out[prior].Priority {
				out[prior].Priority = entry.Priority
			}
			return
		}
		seen[key] = len(out)
		out = append(out, entry)
	}

	addInteger := func(raw string, origin string, priority int) {
		raw = strings.TrimSpace(raw)
		if raw == "" {
			return
		}
		value, ok := functionFuzzParseDictionaryInteger(raw)
		if !ok {
			return
		}
		add(functionFuzzDictEntry{Token: functionFuzzQuoteHexLiteral(raw), Origin: origin + "_int_literal", Priority: priority})
		for _, byteCount := range []int{2, 4, 8} {
			if encoded, ok := functionFuzzEncodeLittleEndian(value, byteCount); ok {
				token := functionFuzzQuoteRawBytes(encoded)
				add(functionFuzzDictEntry{Token: token, Origin: origin + fmt.Sprintf("_le%d", byteCount*8), Priority: priority})
			}
		}
	}

	addString := func(value string, origin string, priority int) {
		token := functionFuzzQuoteRawBytes([]byte(value))
		add(functionFuzzDictEntry{Token: token, Origin: origin + "_string", Priority: priority})
	}

	addIdentifier := func(value string, origin string, priority int) {
		value = strings.TrimSpace(value)
		if value == "" {
			return
		}
		add(functionFuzzDictEntry{Token: functionFuzzQuoteRawBytes([]byte(value)), Origin: origin + "_ident", Priority: priority})
	}

	scanText := func(text string, origin string, basePriority int) {
		if strings.TrimSpace(text) == "" {
			return
		}
		for _, match := range functionFuzzDictIntegerPattern.FindAllString(text, -1) {
			addInteger(match, origin, basePriority)
		}
		for _, match := range functionFuzzDictStringLiteral.FindAllStringSubmatch(text, -1) {
			if len(match) >= 2 && strings.TrimSpace(match[1]) != "" {
				addString(match[1], origin, basePriority-1)
			}
		}
		for _, ident := range functionFuzzDictIdentifierAllCaps.FindAllString(text, -1) {
			addIdentifier(ident, origin, basePriority-2)
		}
	}

	for _, obs := range run.CodeObservations {
		base := 18
		switch strings.ToLower(strings.TrimSpace(obs.Kind)) {
		case "size_guard", "alloc_site", "copy_sink", "probe_sink":
			base = 24
		case "dispatch_guard":
			base = 22
		}
		origin := "obs_" + functionFuzzSanitizeOriginToken(obs.Kind)
		scanText(obs.Evidence, origin, base)
		for _, fact := range obs.ComparisonFacts {
			scanText(fact, origin+"_cmp", base+1)
		}
		for _, focus := range obs.FocusInputs {
			scanText(focus, origin+"_focus", base-1)
		}
	}
	for _, sig := range run.SinkSignals {
		addIdentifier(sig.Name, "sink_"+functionFuzzSanitizeOriginToken(sig.Kind), 16)
		scanText(sig.Reason, "sink_reason", 12)
	}
	for _, scenario := range run.VirtualScenarios {
		scanText(scenario.Title, "scenario_title", 10)
		for _, item := range scenario.ConcreteInputs {
			scanText(item, "scenario_concrete_input", 16)
		}
		for _, item := range scenario.BranchFacts {
			scanText(item, "scenario_branch_fact", 14)
		}
		for _, inv := range scenario.Invariants {
			scanText(inv.Left, "invariant_left", 14)
			scanText(inv.Right, "invariant_right", 14)
			scanText(inv.Detail, "invariant_detail", 10)
		}
		for _, outcome := range scenario.BranchOutcomes {
			scanText(outcome.Predicate, "scenario_branch_pred", 14)
			scanText(outcome.Evidence, "scenario_branch_evi", 12)
		}
		for _, line := range scenario.SourceExcerpt.Snippet {
			scanText(line, "scenario_excerpt", 8)
		}
	}
	for _, param := range run.ParameterStrategies {
		if strings.TrimSpace(param.Name) != "" {
			addIdentifier(param.Name, "param_"+functionFuzzSanitizeOriginToken(param.Class), 6)
		}
	}

	sort.SliceStable(out, func(i, j int) bool {
		if out[i].Priority != out[j].Priority {
			return out[i].Priority > out[j].Priority
		}
		if out[i].Origin != out[j].Origin {
			return out[i].Origin < out[j].Origin
		}
		return out[i].Token < out[j].Token
	})
	if len(out) > 256 {
		out = out[:256]
	}
	return out
}

func functionFuzzRenderDictionaryLine(entry functionFuzzDictEntry) string {
	if strings.TrimSpace(entry.Token) == "" {
		return ""
	}
	label := functionFuzzSanitizeIdentifierForLabel(entry.Origin)
	if label == "" {
		label = "kf_token"
	}
	return fmt.Sprintf("%s=%s", label, entry.Token)
}

func functionFuzzSanitizeIdentifierForLabel(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}
	var b strings.Builder
	for _, r := range value {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_':
			b.WriteRune(r)
		default:
			b.WriteByte('_')
		}
	}
	out := b.String()
	if out == "" {
		return ""
	}
	if out[0] >= '0' && out[0] <= '9' {
		out = "kf_" + out
	}
	if len(out) > 48 {
		out = out[:48]
	}
	return out
}

func functionFuzzSanitizeOriginToken(value string) string {
	out := functionFuzzSanitizeIdentifierForLabel(value)
	if out == "" {
		return "raw"
	}
	return strings.ToLower(out)
}

func functionFuzzParseDictionaryInteger(raw string) (uint64, bool) {
	raw = strings.TrimSpace(raw)
	if raw == "" {
		return 0, false
	}
	negative := false
	if strings.HasPrefix(raw, "-") {
		negative = true
		raw = raw[1:]
	}
	var value uint64
	var err error
	switch {
	case strings.HasPrefix(raw, "0x"), strings.HasPrefix(raw, "0X"):
		value, err = strconv.ParseUint(raw[2:], 16, 64)
	default:
		value, err = strconv.ParseUint(raw, 10, 64)
	}
	if err != nil {
		return 0, false
	}
	if negative {
		value = uint64(-int64(value))
	}
	return value, true
}

func functionFuzzEncodeLittleEndian(value uint64, byteCount int) ([]byte, bool) {
	switch byteCount {
	case 2:
		if value > 0xFFFF && (int64(value) < -0x8000 || int64(value) > 0x7FFF) {
			return nil, false
		}
		out := []byte{byte(value & 0xFF), byte((value >> 8) & 0xFF)}
		return out, true
	case 4:
		if value > 0xFFFFFFFF && (int64(value) < -0x80000000 || int64(value) > 0x7FFFFFFF) {
			return nil, false
		}
		out := make([]byte, 4)
		for i := 0; i < 4; i++ {
			out[i] = byte((value >> (uint(i) * 8)) & 0xFF)
		}
		return out, true
	case 8:
		out := make([]byte, 8)
		for i := 0; i < 8; i++ {
			out[i] = byte((value >> (uint(i) * 8)) & 0xFF)
		}
		return out, true
	}
	return nil, false
}

func functionFuzzQuoteRawBytes(data []byte) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, c := range data {
		switch {
		case c == '\\':
			b.WriteString("\\\\")
		case c == '"':
			b.WriteString("\\\"")
		case c >= 0x20 && c <= 0x7E:
			b.WriteByte(c)
		default:
			b.WriteString(fmt.Sprintf("\\x%02x", c))
		}
	}
	b.WriteByte('"')
	return b.String()
}

func functionFuzzQuoteHexLiteral(raw string) string {
	raw = strings.TrimSpace(raw)
	return functionFuzzQuoteRawBytes([]byte(raw))
}

func functionFuzzWriteSeedCorpusWithProvenance(run FunctionFuzzRun, corpusDir string, manifestPath string, dictionaryPath string) error {
	if err := os.MkdirAll(corpusDir, 0o755); err != nil {
		return err
	}
	seeds := functionFuzzBuildBoundarySeeds(run)
	written := []functionFuzzCorpusSeed{}
	emittedNames := map[string]struct{}{}
	for _, seed := range seeds {
		name := functionFuzzUniqueCorpusName(seed.Name, emittedNames)
		seed.Name = name
		emittedNames[name] = struct{}{}
		path := filepath.Join(corpusDir, name)
		if err := os.WriteFile(path, seed.payload, 0o644); err != nil {
			return err
		}
		hash := sha256.Sum256(seed.payload)
		entry := functionFuzzCorpusSeed{
			Name:        name,
			Scenario:    seed.Scenario,
			ParamClass:  seed.ParamClass,
			ParamName:   seed.ParamName,
			Rule:        seed.Rule,
			Size:        len(seed.payload),
			Sha256:      hex.EncodeToString(hash[:]),
			Origin:      seed.Origin,
			SourceFile:  seed.SourceFile,
			SourceLine:  seed.SourceLine,
			Description: seed.Description,
		}
		written = append(written, entry)
	}
	dictTokens := []string{}
	if strings.TrimSpace(dictionaryPath) != "" {
		if data, err := os.ReadFile(dictionaryPath); err == nil {
			for _, line := range strings.Split(string(data), "\n") {
				line = strings.TrimSpace(line)
				if line == "" || strings.HasPrefix(line, "#") {
					continue
				}
				dictTokens = append(dictTokens, line)
			}
		}
	}
	manifest := functionFuzzCorpusManifest{
		RunID:      run.ID,
		Target:     run.TargetSymbolName,
		Profile:    strings.TrimSpace(run.Execution.Profile),
		Seeds:      written,
		Dictionary: dictTokens,
	}
	manifestData, err := json.MarshalIndent(manifest, "", "  ")
	if err != nil {
		return err
	}
	if err := os.WriteFile(manifestPath, manifestData, 0o644); err != nil {
		return err
	}
	return nil
}

func functionFuzzUniqueCorpusName(base string, existing map[string]struct{}) string {
	base = functionFuzzSanitizeCorpusFilename(base)
	if base == "" {
		base = "seed.bin"
	}
	if _, exists := existing[base]; !exists {
		return base
	}
	dot := strings.LastIndex(base, ".")
	stem := base
	ext := ""
	if dot > 0 {
		stem = base[:dot]
		ext = base[dot:]
	}
	for i := 2; i < 10000; i++ {
		candidate := fmt.Sprintf("%s-%d%s", stem, i, ext)
		if _, exists := existing[candidate]; !exists {
			return candidate
		}
	}
	return base
}

func functionFuzzSanitizeCorpusFilename(value string) string {
	value = strings.TrimSpace(value)
	if value == "" {
		return ""
	}
	var b strings.Builder
	for _, r := range value {
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '-', r == '_', r == '.':
			b.WriteRune(r)
		default:
			b.WriteByte('-')
		}
	}
	out := b.String()
	if !strings.HasSuffix(out, ".bin") {
		out += ".bin"
	}
	if len(out) > 120 {
		out = out[:116] + ".bin"
	}
	return out
}

type functionFuzzBoundarySeed struct {
	Name        string
	Scenario    string
	ParamClass  string
	ParamName   string
	Rule        string
	Origin      string
	SourceFile  string
	SourceLine  int
	Description string
	payload     []byte
}

func functionFuzzBuildBoundarySeeds(run FunctionFuzzRun) []functionFuzzBoundarySeed {
	out := []functionFuzzBoundarySeed{}

	out = append(out, functionFuzzBoundarySeed{
		Name:        "seed-empty.bin",
		Rule:        "empty_input",
		Origin:      "baseline",
		Description: "Zero-length input to probe immediate guards and early-return paths.",
		payload:     []byte{},
	})

	out = append(out, functionFuzzBoundarySeed{
		Name:        "seed-pattern.bin",
		Rule:        "diagnostic_pattern",
		Origin:      "baseline",
		Description: "Mixed byte pattern with sign-flip transitions.",
		payload:     []byte{0x00, 0x01, 0x7f, 0x80, 0xff, 0x10, 0x20, 0x40},
	})

	out = append(out, functionFuzzBoundarySeed{
		Name:        "seed-length-prefix.bin",
		Rule:        "length_prefix_header",
		Origin:      "baseline",
		Description: "4-byte little-endian length-prefix style header used as a default structural fallback.",
		payload: []byte{
			0x04, 0x00, 0x00, 0x00,
			0x10, 0x20, 0x30, 0x40,
			0xff, 0xee, 0xdd, 0xcc,
			0x00, 0x00, 0x00, 0x01,
		},
	})

	for _, param := range run.ParameterStrategies {
		seeds := functionFuzzSeedsForParameter(param)
		out = append(out, seeds...)
	}

	scenarios := run.VirtualScenarios
	if len(scenarios) > 8 {
		scenarios = scenarios[:8]
	}
	for idx, scenario := range scenarios {
		seeds := functionFuzzSeedsForScenario(idx, scenario, run.ParameterStrategies)
		out = append(out, seeds...)
	}
	return out
}

func functionFuzzSeedsForParameter(param FunctionFuzzParamStrategy) []functionFuzzBoundarySeed {
	class := strings.ToLower(strings.TrimSpace(param.Class))
	name := functionFuzzSanitizeIdentifierForLabel(param.Name)
	if name == "" {
		name = "p" + strconv.Itoa(param.Index)
	}
	prefix := fmt.Sprintf("seed-param-%d-%s", param.Index, strings.ToLower(name))
	if len(prefix) > 80 {
		prefix = prefix[:80]
	}
	mk := func(suffix string, rule string, payload []byte, description string) functionFuzzBoundarySeed {
		return functionFuzzBoundarySeed{
			Name:        prefix + "-" + suffix + ".bin",
			Rule:        rule,
			ParamClass:  class,
			ParamName:   param.Name,
			Origin:      "param_strategy",
			Description: description,
			payload:     payload,
		}
	}
	out := []functionFuzzBoundarySeed{}
	switch class {
	case "length", "scalar_int":
		out = append(out, mk("zero", "scalar_zero", functionFuzzLEBytes(0, 4), "Zero-value scalar."))
		out = append(out, mk("one", "scalar_one", functionFuzzLEBytes(1, 4), "Minimal positive scalar."))
		out = append(out, mk("max-u32", "scalar_max_u32", functionFuzzLEBytes(0xFFFFFFFF, 4), "Unsigned 32-bit max for overflow probing."))
		out = append(out, mk("max-minus-1", "scalar_max_minus_1", functionFuzzLEBytes(0xFFFFFFFE, 4), "max-1 boundary."))
		out = append(out, mk("signed-min", "scalar_signed_min", functionFuzzLEBytes(0x80000000, 4), "Signed 32-bit min (sign-flip probe)."))
		out = append(out, mk("signed-max", "scalar_signed_max", functionFuzzLEBytes(0x7FFFFFFF, 4), "Signed 32-bit max."))
		out = append(out, mk("off-by-one", "scalar_off_by_one", functionFuzzLEBytes(0x10001, 4), "Common boundary just above 16-bit cap."))
		out = append(out, mk("very-large", "scalar_very_large", functionFuzzLEBytes(0xCAFEBABE, 4), "Large mid-range value."))
	case "buffer", "pointer", "string", "opaque":
		out = append(out, mk("empty", "buffer_empty", []byte{}, "Empty buffer to stress early-out paths."))
		out = append(out, mk("byte-one", "buffer_one_byte", []byte{0xCC}, "Single-byte payload."))
		out = append(out, mk("short-header", "buffer_short_header", []byte{0x10, 0x00, 0x00, 0x00, 0xAA, 0xBB}, "Short-header payload (claimed size > actual)."))
		out = append(out, mk("null-term-injected", "buffer_null_term_injected", []byte{0x41, 0x42, 0x00, 0x43, 0x44}, "Embedded NUL terminator inside payload."))
		out = append(out, mk("oversized-4k", "buffer_oversized_4k", functionFuzzRepeatBytes(0x55, 4096), "4 KiB oversized buffer."))
		out = append(out, mk("very-large-64k", "buffer_very_large_64k", functionFuzzRepeatBytes(0x5A, 65536), "64 KiB very large buffer."))
		out = append(out, mk("ascii-path-like", "buffer_path_like", []byte("\\??\\C:\\path\\to\\object"), "Path-like ASCII payload."))
		out = append(out, mk("format-tokens", "buffer_format_tokens", []byte("%s %x %n %p"), "Format-string token bait."))
	case "enum_or_flags":
		out = append(out, mk("zero", "enum_zero", functionFuzzLEBytes(0, 4), "All-zero enum."))
		out = append(out, mk("all-bits", "enum_all_bits", functionFuzzLEBytes(0xFFFFFFFF, 4), "All-bits-set flag mask."))
		out = append(out, mk("high-bit", "enum_high_bit", functionFuzzLEBytes(0x80000000, 4), "High-bit-only flag."))
		out = append(out, mk("single-bit", "enum_single_bit", functionFuzzLEBytes(1, 4), "Single low bit."))
		out = append(out, mk("dense-bits", "enum_dense_bits", functionFuzzLEBytes(0x55555555, 4), "Alternating dense bits."))
	case "handle":
		out = append(out, mk("zero", "handle_zero", functionFuzzLEBytes(0, 8), "Null handle."))
		out = append(out, mk("invalid-handle", "handle_invalid", functionFuzzLEBytes(0xFFFFFFFFFFFFFFFF, 8), "INVALID_HANDLE_VALUE."))
		out = append(out, mk("pseudo-handle", "handle_pseudo", functionFuzzLEBytes(0xFFFFFFFFFFFFFFFE, 8), "Pseudo current-process handle (~-1)."))
	case "boolean":
		out = append(out, mk("false", "bool_false", []byte{0x00}, "Boolean false."))
		out = append(out, mk("true", "bool_true", []byte{0x01}, "Boolean true."))
		out = append(out, mk("nonzero", "bool_nonzero", []byte{0xFF}, "Boolean stored as 0xFF."))
	case "scalar_float":
		out = append(out, mk("zero", "float_zero", []byte{0, 0, 0, 0}, "Float zero."))
		out = append(out, mk("nan", "float_nan", []byte{0x00, 0x00, 0xC0, 0x7F}, "Quiet NaN."))
		out = append(out, mk("inf", "float_inf", []byte{0x00, 0x00, 0x80, 0x7F}, "Positive infinity."))
	case "container":
		out = append(out, mk("empty-container", "container_empty", functionFuzzLEBytes(0, 4), "Empty container count=0."))
		out = append(out, mk("single-item", "container_single", append(functionFuzzLEBytes(1, 4), 0xAA), "Single element."))
		out = append(out, mk("large-count", "container_large", functionFuzzLEBytes(0xFFFFFFFF, 4), "Claimed huge element count."))
	}
	return out
}

// functionFuzzSeedsForScenario emits a structured seed for a virtual scenario.
//
// The seed bytes are laid out exactly the way the generated harness's
// FuzzInputView decodes parameters in order (see renderFunctionFuzzHarness and
// functionFuzzHarnessParamLines): typed scalars little-endian, an 8-byte size_t
// length prefix for byte vectors/strings, and the buffer<->length coupling that
// the harness applies via functionFuzzHarnessCoupledLengthLines. The values are
// populated from the scenario's real data - the first parseable comparison
// constant found in its invariants/concrete inputs/branch facts plus per-class
// boundary values - not from the English ConcreteInputs prose (that prose stays
// in the report). If the scenario has no parameters to encode against, no seed
// is emitted rather than writing prose bytes.
func functionFuzzSeedsForScenario(index int, scenario FunctionFuzzVirtualScenario, params []FunctionFuzzParamStrategy) []functionFuzzBoundarySeed {
	if len(params) == 0 {
		return nil
	}
	title := functionFuzzSanitizeIdentifierForLabel(scenario.Title)
	if title == "" {
		title = "scenario"
	}
	if len(title) > 48 {
		title = title[:48]
	}
	base := fmt.Sprintf("seed-scenario-%02d-%s", index+1, strings.ToLower(title))

	desync := functionFuzzScenarioTargetsSizeDesync(scenario)
	targetConst, hasConst := functionFuzzScenarioPrimaryConstant(scenario)

	payload, ok := functionFuzzEncodeScenarioPayload(params, desync, targetConst, hasConst)
	if !ok {
		// No parameter layout could be encoded for this scenario. Per the
		// design, omit a seed rather than fall back to prose bytes.
		return nil
	}

	description := "Structured multi-parameter seed encoded for the harness FuzzInputView decode order."
	if desync {
		description = "Structured seed with a deliberate buffer<->length size desync for the harness decode order."
	}
	out := []functionFuzzBoundarySeed{
		{
			Name:        base + ".bin",
			Scenario:    scenario.Title,
			Rule:        "scenario_concrete_inputs",
			Origin:      "virtual_scenario",
			SourceFile:  scenario.SourceExcerpt.File,
			SourceLine:  scenario.SourceExcerpt.FocusLine,
			Description: description,
			payload:     payload,
		},
	}
	return out
}

// functionFuzzScenarioTargetsSizeDesync reports whether a scenario is about a
// buffer/length size disagreement, in which case the seed should encode a
// declared length that deliberately differs from the real buffer length.
func functionFuzzScenarioTargetsSizeDesync(scenario FunctionFuzzVirtualScenario) bool {
	title := strings.ToLower(strings.TrimSpace(scenario.Title))
	if containsAny(title,
		"attacker-controlled size",
		"short backing store",
		"buffer and scalar size",
		"conflicting scalar size",
		"allocation size",
		"size desync",
		"size drift") {
		return true
	}
	for _, inv := range scenario.Invariants {
		kind := strings.ToLower(strings.TrimSpace(inv.Kind))
		if containsAny(kind, "size", "buffer_size_contract", "guard_use_size") {
			return true
		}
	}
	return false
}

// functionFuzzScenarioPrimaryConstant extracts the first parseable integer
// constant the scenario refers to, scanning its invariants, concrete inputs,
// and branch facts in that priority order. This is the comparison constant the
// seed should embed into the leading typed scalar/length parameter so the seed
// exercises the relevant boundary.
func functionFuzzScenarioPrimaryConstant(scenario FunctionFuzzVirtualScenario) (uint64, bool) {
	candidates := []string{}
	for _, inv := range scenario.Invariants {
		candidates = append(candidates, inv.Detail, inv.Left, inv.Right)
	}
	candidates = append(candidates, scenario.ConcreteInputs...)
	candidates = append(candidates, scenario.BranchFacts...)
	for _, text := range candidates {
		if strings.TrimSpace(text) == "" {
			continue
		}
		for _, match := range functionFuzzDictIntegerPattern.FindAllString(text, -1) {
			if value, ok := functionFuzzParseDictionaryInteger(match); ok {
				return value, true
			}
		}
	}
	return 0, false
}

// functionFuzzScalarByteWidth maps a C scalar raw type to the byte width the
// harness will read via ReadScalar<rawType> (sizeof(rawType)). It covers the
// common fixed-width and Windows typedef widths and defaults to 4 bytes.
func functionFuzzScalarByteWidth(rawType string) int {
	lower := strings.ToLower(strings.TrimSpace(rawType))
	lower = strings.TrimPrefix(lower, "const ")
	lower = strings.TrimSpace(lower)
	switch {
	case lower == "":
		return 4
	case containsAny(lower, "int8", "uint8", "int8_t", "uint8_t", "char", "byte", "bool", "uchar", "boolean"):
		return 1
	case containsAny(lower, "int16", "uint16", "int16_t", "uint16_t", "short", "wchar", "ushort", "word"):
		return 2
	case containsAny(lower, "int64", "uint64", "int64_t", "uint64_t", "longlong", "size_t", " size", "ptr", "intptr", "uintptr", "ulong64", "long64", "qword", "double"):
		return 8
	case containsAny(lower, "int32", "uint32", "int32_t", "uint32_t", "long", "ulong", "dword", "float", "int", "uint"):
		return 4
	default:
		return 4
	}
}

// functionFuzzScenarioBoundaryForClass returns the per-class boundary value used
// when a scenario does not pin a concrete comparison constant onto a scalar.
func functionFuzzScenarioBoundaryForClass(class string) uint64 {
	switch strings.ToLower(strings.TrimSpace(class)) {
	case "length", "scalar_int":
		return 0xFFFFFFFF
	case "enum_or_flags":
		return 0x80000000
	default:
		return 0
	}
}

// functionFuzzEncodeScenarioPayload builds the structured seed bytes for the
// scenario by walking the parameters in the SAME emit order the harness uses,
// including the coupled-length deferral (a length related to a later buffer is
// emitted after that buffer). Each parameter contributes the bytes its decode
// helper consumes. The first scalar/length parameter receives targetConst (when
// present) so the extracted comparison constant lands at a decodable offset.
func functionFuzzEncodeScenarioPayload(params []FunctionFuzzParamStrategy, desync bool, targetConst uint64, hasConst bool) ([]byte, bool) {
	// Resolve buffer<->length couplings the same way the harness does, keyed by
	// the length parameter name.
	coupledLengths := map[string]functionFuzzParamPair{}
	coupledBuffers := map[string]struct{}{}
	for _, pair := range functionFuzzRelatedBufferLengthPairs(params) {
		lenKey := strings.ToLower(strings.TrimSpace(pair.Length.Name))
		if lenKey == "" {
			continue
		}
		if _, exists := coupledLengths[lenKey]; !exists {
			coupledLengths[lenKey] = pair
		}
		coupledBuffers[strings.ToLower(strings.TrimSpace(pair.Buffer.Name))] = struct{}{}
	}

	var payload []byte
	encoded := false
	constUsed := false
	emitted := map[string]struct{}{}
	bufferLen := map[string]int{}

	// emitScalarConstant places targetConst into the first scalar/length that can
	// hold it, otherwise the per-class boundary value.
	emitScalar := func(class string, width int) {
		value := functionFuzzScenarioBoundaryForClass(class)
		if hasConst && !constUsed {
			value = targetConst
			constUsed = true
		}
		payload = append(payload, functionFuzzLEBytes(value, width)...)
	}

	var deferred []functionFuzzParamPair
	flushDeferred := func() {
		for i := 0; i < len(deferred); {
			pair := deferred[i]
			bufKey := strings.ToLower(strings.TrimSpace(pair.Buffer.Name))
			if realLen, ready := bufferLen[bufKey]; ready {
				payload = append(payload, functionFuzzEncodeCoupledLength(realLen, desync)...)
				emitted[strings.ToLower(strings.TrimSpace(pair.Length.Name))] = struct{}{}
				encoded = true
				deferred = append(deferred[:i], deferred[i+1:]...)
				continue
			}
			i++
		}
	}

	for _, item := range params {
		itemKey := strings.ToLower(strings.TrimSpace(item.Name))
		class := strings.ToLower(strings.TrimSpace(item.Class))

		// Coupled length: encode it relative to its paired buffer's real length.
		if pair, ok := coupledLengths[itemKey]; ok && class == "length" {
			bufKey := strings.ToLower(strings.TrimSpace(pair.Buffer.Name))
			if realLen, ready := bufferLen[bufKey]; ready {
				payload = append(payload, functionFuzzEncodeCoupledLength(realLen, desync)...)
				emitted[itemKey] = struct{}{}
				encoded = true
			} else {
				deferred = append(deferred, pair)
			}
			continue
		}

		switch class {
		case "boolean":
			payload = append(payload, 0x01)
			encoded = true
		case "scalar_int", "scalar_float":
			emitScalar(class, functionFuzzScalarByteWidth(item.RawType))
			encoded = true
		case "enum_or_flags":
			emitScalar(class, 4)
			encoded = true
		case "length":
			// Lone length: ReadSize reads an 8-byte size_t.
			emitScalar(class, 8)
			encoded = true
		case "string", "buffer", "pointer", "container":
			body := functionFuzzScenarioVectorBody(class)
			declared := len(body)
			_, isCoupled := coupledBuffers[itemKey]
			if desync && !isCoupled {
				// Declare a length larger than the bytes actually present so the
				// harness decodes a length that disagrees with the payload. A
				// buffer that is coupled to a length keeps a consistent declared
				// prefix so it does not consume the trailing coupled-length
				// flag/delta bytes - that desync is expressed by the coupled
				// length below instead.
				declared = len(body) + 0x40
			}
			payload = append(payload, functionFuzzLEBytes(uint64(declared), 8)...)
			payload = append(payload, body...)
			bufferLen[itemKey] = len(body)
			encoded = true
		case "handle", "object":
			// The harness emits a zero-initialized placeholder and consumes no
			// input bytes for these classes, so contribute nothing.
		default:
			// Unknown class: no decode bytes are consumed by the harness.
		}
		emitted[itemKey] = struct{}{}
		flushDeferred()
	}

	// Any coupled length whose buffer never appeared falls back to an independent
	// 8-byte size_t, matching the harness defensive fallback.
	for _, pair := range deferred {
		payload = append(payload, functionFuzzLEBytes(functionFuzzScenarioBoundaryForClass("length"), 8)...)
		emitted[strings.ToLower(strings.TrimSpace(pair.Length.Name))] = struct{}{}
		encoded = true
	}

	if !encoded {
		return nil, false
	}
	return payload, true
}

// functionFuzzEncodeCoupledLength encodes the input bytes a coupled length
// consumes in the harness. The length value itself is derived from the buffer's
// real .size() at run time, so only the desync-flag byte (and an optional delta
// byte) come from the seed. A consistent seed sets the flag so (flag & 0x07) is
// non-zero, keeping the derived length equal to the buffer length. A desync seed
// clears those low bits and supplies a non-zero delta so the harness perturbs
// the length away from the buffer's real size.
func functionFuzzEncodeCoupledLength(realBufferLen int, desync bool) []byte {
	if !desync {
		// (0x01 & 0x07) != 0 -> harness keeps length == buffer.size().
		return []byte{0x01}
	}
	// (0x00 & 0x07) == 0 -> harness takes the desync path and reads a delta byte.
	// Use +1 so the declared length exceeds the buffer's real length.
	return []byte{0x00, 0x01}
}

// functionFuzzScenarioVectorBody returns a small, class-appropriate payload body
// for a byte-vector/string parameter in a scenario seed.
func functionFuzzScenarioVectorBody(class string) []byte {
	switch strings.ToLower(strings.TrimSpace(class)) {
	case "string":
		return []byte("AAAA")
	default:
		return []byte{0x41, 0x41, 0x41, 0x41}
	}
}

func functionFuzzRepeatBytes(b byte, count int) []byte {
	if count <= 0 {
		return []byte{}
	}
	out := make([]byte, count)
	for i := range out {
		out[i] = b
	}
	return out
}

func functionFuzzLEBytes(value uint64, byteCount int) []byte {
	if byteCount <= 0 {
		return []byte{}
	}
	out := make([]byte, byteCount)
	for i := 0; i < byteCount; i++ {
		out[i] = byte((value >> (uint(i) * 8)) & 0xFF)
	}
	return out
}
